language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - php vendor/squizlabs/php_codesniffer/scripts/phpcs src/ --standard=PSR2 --report=summary